export const cityStates = [
  // Lynn itself
  'Lynn, MA',
  // Within ~5 miles
  'Swampscott, MA',
  'Saugus, MA',
  'Nahant, MA',
  'Revere, MA',
  'Salem, MA',
  'Marblehead, MA',
  'Peabody, MA',
  // Within ~10 miles
  'Beverly, MA',
  'Chelsea, MA',
  'Danvers, MA',
  'Everett, MA',
  'Lynnfield, MA',
  'Malden, MA',
  'Medford, MA',
  'Somerville, MA',
  'Winthrop, MA',
  // Within ~15 miles
  'Andover, MA',
  'Arlington, MA',
  'Boston, MA',
  'Braintree, MA',
  'Burlington, MA',
  'Cambridge, MA',
  'Gloucester, MA',
  'Hamilton, MA',
  'Ipswich, MA',
  'Lawrence, MA',
  'Lexington, MA',
  'Melrose, MA',
  'Methuen, MA',
  'Middleton, MA',
  'North Andover, MA',
  'Reading, MA',
  'Rockport, MA',
  'Stoneham, MA',
  'Topsfield, MA',
  'Wakefield, MA',
  'Wenham, MA',
  'Weston, MA',
  'Woburn, MA',
  // Within ~20 miles
  'Amesbury, MA',
  'Belmont, MA',
  'Boxford, MA',
  'Essex, MA',
  'Georgetown, MA',
  'Haverhill, MA',
  'Manchester-by-the-Sea, MA',
  'Merrimac, MA',
  'Newburyport, MA',
  'Newton, MA',
  'Newtonville, MA',
  'Quincy, MA',
  'Rowley, MA',
  'Watertown, MA',
  'West Newton, MA',
  'Winchester, MA'
]
